name: Music Sync

on:
  schedule:
    # Запуск каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-cache-dependency-path: true

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Spondex Sync
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: poetry run python main.py
